"""empty message

Revision ID: 5e52b525ac3f
Revises: 
Create Date: 2026-01-24 02:42:17.975845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '5e52b525ac3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _index_exists(table_name: str, index_name: str) -> bool:
    """Check if an index exists on a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    indexes = inspector.get_indexes(table_name)
    return any(idx['name'] == index_name for idx in indexes)


def _constraint_exists(table_name: str, constraint_name: str) -> bool:
    """Check if a constraint exists on a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    constraints = inspector.get_unique_constraints(table_name)
    return any(uc['name'] == constraint_name for uc in constraints)


def _foreign_key_exists(table_name: str, constraint_name: str = None) -> bool:
    """Check if a foreign key constraint exists on a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    foreign_keys = inspector.get_foreign_keys(table_name)
    if constraint_name:
        return any(fk['name'] == constraint_name for fk in foreign_keys)
    return len(foreign_keys) > 0


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not _index_exists('bot', 'ix_bot_gmt_deleted'):
        op.create_index(op.f('ix_bot_gmt_deleted'), 'bot', ['gmt_deleted'], unique=False)
    if not _index_exists('bot', 'ix_bot_status'):
        op.create_index(op.f('ix_bot_status'), 'bot', ['status'], unique=False)
    if not _index_exists('bot', 'ix_bot_user'):
        op.create_index(op.f('ix_bot_user'), 'bot', ['user'], unique=False)
    if not _index_exists('chat', 'ix_chat_bot_id'):
        op.create_index(op.f('ix_chat_bot_id'), 'chat', ['bot_id'], unique=False)
    if not _index_exists('chat', 'ix_chat_gmt_deleted'):
        op.create_index(op.f('ix_chat_gmt_deleted'), 'chat', ['gmt_deleted'], unique=False)
    if not _index_exists('chat', 'ix_chat_status'):
        op.create_index(op.f('ix_chat_status'), 'chat', ['status'], unique=False)
    if not _index_exists('chat', 'ix_chat_user'):
        op.create_index(op.f('ix_chat_user'), 'chat', ['user'], unique=False)
    if not _constraint_exists('chat', 'uq_chat_bot_peer_deleted'):
        op.create_unique_constraint('uq_chat_bot_peer_deleted', 'chat', ['bot_id', 'peer_type', 'peer_id', 'gmt_deleted'])
    if not _index_exists('chat_message', 'ix_chat_message_chat_id'):
        op.create_index(op.f('ix_chat_message_chat_id'), 'chat_message', ['chat_id'], unique=False)
    if not _index_exists('chat_message', 'ix_chat_message_created_at'):
        op.create_index(op.f('ix_chat_message_created_at'), 'chat_message', ['created_at'], unique=False)
    if not _index_exists('chat_message', 'ix_chat_message_message_id'):
        op.create_index(op.f('ix_chat_message_message_id'), 'chat_message', ['message_id'], unique=False)
    if not _index_exists('collection', 'ix_collection_gmt_deleted'):
        op.create_index(op.f('ix_collection_gmt_deleted'), 'collection', ['gmt_deleted'], unique=False)
    if not _index_exists('collection', 'ix_collection_status'):
        op.create_index(op.f('ix_collection_status'), 'collection', ['status'], unique=False)
    if not _index_exists('collection', 'ix_collection_user'):
        op.create_index(op.f('ix_collection_user'), 'collection', ['user'], unique=False)
    if not _index_exists('document', 'ix_document_collection_id'):
        op.create_index(op.f('ix_document_collection_id'), 'document', ['collection_id'], unique=False)
    if not _index_exists('document', 'ix_document_content_hash'):
        op.create_index(op.f('ix_document_content_hash'), 'document', ['content_hash'], unique=False)
    if not _index_exists('document', 'ix_document_gmt_deleted'):
        op.create_index(op.f('ix_document_gmt_deleted'), 'document', ['gmt_deleted'], unique=False)
    if not _index_exists('document', 'ix_document_status'):
        op.create_index(op.f('ix_document_status'), 'document', ['status'], unique=False)
    if not _index_exists('document', 'ix_document_user'):
        op.create_index(op.f('ix_document_user'), 'document', ['user'], unique=False)
    if not _constraint_exists('document', 'uq_document_collection_name_deleted'):
        op.create_unique_constraint('uq_document_collection_name_deleted', 'document', ['collection_id', 'name', 'gmt_deleted'])
    if not _index_exists('document_index', 'ix_document_index_document_id'):
        op.create_index(op.f('ix_document_index_document_id'), 'document_index', ['document_id'], unique=False)
    if not _index_exists('document_index', 'ix_document_index_id'):
        op.create_index(op.f('ix_document_index_id'), 'document_index', ['id'], unique=False)
    if not _index_exists('document_index', 'ix_document_index_index_type'):
        op.create_index(op.f('ix_document_index_index_type'), 'document_index', ['index_type'], unique=False)
    if not _index_exists('document_index', 'ix_document_index_status'):
        op.create_index(op.f('ix_document_index_status'), 'document_index', ['status'], unique=False)
    if not _constraint_exists('document_index', 'uq_document_index'):
        op.create_unique_constraint('uq_document_index', 'document_index', ['document_id', 'index_type'])
    if not _index_exists('llm_provider', 'ix_llm_provider_user_id'):
        op.create_index(op.f('ix_llm_provider_user_id'), 'llm_provider', ['user_id'], unique=False)
    if not _index_exists('message_feedback', 'ix_message_feedback_gmt_deleted'):
        op.create_index(op.f('ix_message_feedback_gmt_deleted'), 'message_feedback', ['gmt_deleted'], unique=False)
    if not _index_exists('message_feedback', 'ix_message_feedback_status'):
        op.create_index(op.f('ix_message_feedback_status'), 'message_feedback', ['status'], unique=False)
    if not _index_exists('message_feedback', 'ix_message_feedback_user'):
        op.create_index(op.f('ix_message_feedback_user'), 'message_feedback', ['user'], unique=False)
    if not _constraint_exists('message_feedback', 'uq_feedback_chat_message_deleted'):
        op.create_unique_constraint('uq_feedback_chat_message_deleted', 'message_feedback', ['chat_id', 'message_id', 'gmt_deleted'])
    if not _index_exists('model_service_provider', 'ix_model_service_provider_name'):
        op.create_index(op.f('ix_model_service_provider_name'), 'model_service_provider', ['name'], unique=False)
    if not _index_exists('model_service_provider', 'ix_model_service_provider_status'):
        op.create_index(op.f('ix_model_service_provider_status'), 'model_service_provider', ['status'], unique=False)
    if not _constraint_exists('model_service_provider', 'uq_model_service_provider_name_deleted'):
        op.create_unique_constraint('uq_model_service_provider_name_deleted', 'model_service_provider', ['name', 'gmt_deleted'])
    if not _index_exists('oauth_account', 'ix_oauth_account_account_id'):
        op.create_index(op.f('ix_oauth_account_account_id'), 'oauth_account', ['account_id'], unique=False)
    if not _index_exists('oauth_account', 'ix_oauth_account_oauth_name'):
        op.create_index(op.f('ix_oauth_account_oauth_name'), 'oauth_account', ['oauth_name'], unique=False)
    # Check if foreign key already exists by checking if any FK exists on oauth_account.user_id
    bind = op.get_bind()
    inspector = inspect(bind)
    fks = inspector.get_foreign_keys('oauth_account')
    has_user_fk = any(fk['constrained_columns'] == ['user_id'] and fk['referred_table'] == 'user' for fk in fks)
    if not has_user_fk:
        op.create_foreign_key(None, 'oauth_account', 'user', ['user_id'], ['id'], ondelete='cascade')
    if not _index_exists('user', 'ix_user_chat_collection_id'):
        op.create_index(op.f('ix_user_chat_collection_id'), 'user', ['chat_collection_id'], unique=False)
    # Check unique constraints on user table
    user_constraints = inspector.get_unique_constraints('user')
    has_email_constraint = any(uc['column_names'] == ['email'] for uc in user_constraints)
    has_username_constraint = any(uc['column_names'] == ['username'] for uc in user_constraints)
    if not has_email_constraint:
        op.create_unique_constraint(None, 'user', ['email'])
    if not has_username_constraint:
        op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_chat_collection_id'), table_name='user')
    op.drop_constraint(None, 'oauth_account', type_='foreignkey')
    op.drop_index(op.f('ix_oauth_account_oauth_name'), table_name='oauth_account')
    op.drop_index(op.f('ix_oauth_account_account_id'), table_name='oauth_account')
    op.drop_constraint('uq_model_service_provider_name_deleted', 'model_service_provider', type_='unique')
    op.drop_index(op.f('ix_model_service_provider_status'), table_name='model_service_provider')
    op.drop_index(op.f('ix_model_service_provider_name'), table_name='model_service_provider')
    op.drop_constraint('uq_feedback_chat_message_deleted', 'message_feedback', type_='unique')
    op.drop_index(op.f('ix_message_feedback_user'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_status'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_gmt_deleted'), table_name='message_feedback')
    op.drop_index(op.f('ix_llm_provider_user_id'), table_name='llm_provider')
    op.drop_constraint('uq_document_index', 'document_index', type_='unique')
    op.drop_index(op.f('ix_document_index_status'), table_name='document_index')
    op.drop_index(op.f('ix_document_index_index_type'), table_name='document_index')
    op.drop_index(op.f('ix_document_index_id'), table_name='document_index')
    op.drop_index(op.f('ix_document_index_document_id'), table_name='document_index')
    op.drop_constraint('uq_document_collection_name_deleted', 'document', type_='unique')
    op.drop_index(op.f('ix_document_user'), table_name='document')
    op.drop_index(op.f('ix_document_status'), table_name='document')
    op.drop_index(op.f('ix_document_gmt_deleted'), table_name='document')
    op.drop_index(op.f('ix_document_content_hash'), table_name='document')
    op.drop_index(op.f('ix_document_collection_id'), table_name='document')
    op.drop_index(op.f('ix_collection_user'), table_name='collection')
    op.drop_index(op.f('ix_collection_status'), table_name='collection')
    op.drop_index(op.f('ix_collection_gmt_deleted'), table_name='collection')
    op.drop_index(op.f('ix_chat_message_message_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_created_at'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_chat_id'), table_name='chat_message')
    op.drop_constraint('uq_chat_bot_peer_deleted', 'chat', type_='unique')
    op.drop_index(op.f('ix_chat_user'), table_name='chat')
    op.drop_index(op.f('ix_chat_status'), table_name='chat')
    op.drop_index(op.f('ix_chat_gmt_deleted'), table_name='chat')
    op.drop_index(op.f('ix_chat_bot_id'), table_name='chat')
    op.drop_index(op.f('ix_bot_user'), table_name='bot')
    op.drop_index(op.f('ix_bot_status'), table_name='bot')
    op.drop_index(op.f('ix_bot_gmt_deleted'), table_name='bot')
    # ### end Alembic commands ###
