"""add workflow tables

Revision ID: aac9cd19df75
Revises: 8ed9487ae8c9
Create Date: 2026-01-30 15:32:09.949299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac9cd19df75'
down_revision: Union[str, None] = '8ed9487ae8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('graph', sa.JSON(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_gmt_deleted'), 'workflow', ['gmt_deleted'], unique=False)
    op.create_index(op.f('ix_workflow_status'), 'workflow', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_user'), 'workflow', ['user'], unique=False)
    op.create_table('workflow_version',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('workflow_id', sa.String(length=24), nullable=False),
    sa.Column('user', sa.String(length=256), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('graph', sa.JSON(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('save_type', sa.String(length=64), nullable=False),
    sa.Column('autosave_metadata', sa.JSON(), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'version', name='uq_workflow_version')
    )
    op.create_index(op.f('ix_workflow_version_user'), 'workflow_version', ['user'], unique=False)
    op.create_index(op.f('ix_workflow_version_workflow_id'), 'workflow_version', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_version_workflow_id'), table_name='workflow_version')
    op.drop_index(op.f('ix_workflow_version_user'), table_name='workflow_version')
    op.drop_table('workflow_version')
    op.drop_index(op.f('ix_workflow_user'), table_name='workflow')
    op.drop_index(op.f('ix_workflow_status'), table_name='workflow')
    op.drop_index(op.f('ix_workflow_gmt_deleted'), table_name='workflow')
    op.drop_table('workflow')
    # ### end Alembic commands ###
