"""auto migration

Revision ID: 91665c36ab05
Revises: 13b4160e4eaa
Create Date: 2026-03-10 02:03:50.361100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.exc import OperationalError

# revision identifiers, used by Alembic.
revision: str = '91665c36ab05'
down_revision: Union[str, None] = '13b4160e4eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    def safe_create_index(name, table_name, columns, unique=False):
        """Create index, silently ignore MySQL duplicate-key errors."""
        try:
            op.create_index(name, table_name, columns, unique=unique)
        except OperationalError as e:
            msg = str(e).lower()
            # MySQL duplicate index error code 1061
            if "1061" in msg or "duplicate key name" in msg:
                return
            raise

    def safe_create_unique_constraint(name, table_name, columns):
        """Create unique constraint, silently ignore MySQL duplicate-key errors."""
        try:
            op.create_unique_constraint(name, table_name, columns)
        except OperationalError as e:
            msg = str(e).lower()
            if "1061" in msg or "duplicate key name" in msg:
                return
            raise

    # MySQL 上一次执行该 migration 时可能已经成功创建了 api_key 表，
    # 但在后续步骤报错导致 alembic_version 没有更新，从而出现“表已存在”的错误。
    # 这里做一次存在性检查，避免重复创建。
    if not inspector.has_table('api_key'):
        op.create_table(
            'api_key',
            sa.Column('id', sa.String(length=24), nullable=False),
            sa.Column('key', sa.String(length=64), nullable=False),
            sa.Column('user', sa.String(length=256), nullable=False),
            sa.Column('description', sa.String(length=256), nullable=True),
            sa.Column('status', sa.String(length=50), nullable=False),
            sa.Column('is_system', sa.Boolean(), nullable=False),
            sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
            sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
            sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
            sa.PrimaryKeyConstraint('id'),
        )
        safe_create_index(op.f('ix_api_key_gmt_deleted'), 'api_key', ['gmt_deleted'], unique=False)
        safe_create_index(op.f('ix_api_key_is_system'), 'api_key', ['is_system'], unique=False)
        safe_create_index(op.f('ix_api_key_status'), 'api_key', ['status'], unique=False)
        safe_create_index(op.f('ix_api_key_user'), 'api_key', ['user'], unique=False)
    # NOTE: Indexes on the existing `agent` table already exist in the database
    # (ix_agent_gmt_deleted, ix_agent_status, ix_agent_user). Creating them again
    # would cause "Duplicate key name" errors on MySQL, so we intentionally skip
    # re-creating them here.
    #
    # 同样地，`audit_log` 表上的 idx_audit_* 系列索引已经在现有 MySQL
    # 实例中创建，而且带有 BLOCK_SIZE / LOCAL 等 MySQL 特有选项，SQLAlchemy
    # 无法正确反射出来。为避免重复创建导致 1061 错误，这个 migration
    # 不再尝试管理 `audit_log` 的这些索引，仅依赖现有数据库结构。
    op.alter_column('chat', 'agent_id',
               existing_type=mysql.VARCHAR(length=24),
               nullable=False)
    safe_create_index(op.f('ix_chat_agent_id'), 'chat', ['agent_id'], unique=False)
    safe_create_index(op.f('ix_chat_gmt_deleted'), 'chat', ['gmt_deleted'], unique=False)
    safe_create_index(op.f('ix_chat_status'), 'chat', ['status'], unique=False)
    safe_create_index(op.f('ix_chat_user'), 'chat', ['user'], unique=False)
    safe_create_unique_constraint('uq_chat_agent_peer_deleted', 'chat', ['agent_id', 'peer_type', 'peer_id', 'gmt_deleted'])
    safe_create_index(op.f('ix_chat_message_chat_id'), 'chat_message', ['chat_id'], unique=False)
    safe_create_index(op.f('ix_chat_message_created_at'), 'chat_message', ['created_at'], unique=False)
    safe_create_index(op.f('ix_chat_message_message_id'), 'chat_message', ['message_id'], unique=False)
    safe_create_index(op.f('ix_collection_gmt_deleted'), 'collection', ['gmt_deleted'], unique=False)
    safe_create_index(op.f('ix_collection_status'), 'collection', ['status'], unique=False)
    safe_create_index(op.f('ix_collection_user'), 'collection', ['user'], unique=False)
    safe_create_index('idx_collection_marketplace_collection_id', 'collection_marketplace', ['collection_id'], unique=False)
    safe_create_index('idx_collection_marketplace_gmt_deleted', 'collection_marketplace', ['gmt_deleted'], unique=False)
    safe_create_index('idx_collection_marketplace_list', 'collection_marketplace', ['status', 'gmt_created'], unique=False)
    safe_create_index('idx_collection_marketplace_status', 'collection_marketplace', ['status'], unique=False)
    safe_create_unique_constraint('uq_collection_marketplace_collection', 'collection_marketplace', ['collection_id'])
    safe_create_index(op.f('ix_document_collection_id'), 'document', ['collection_id'], unique=False)
    safe_create_index(op.f('ix_document_content_hash'), 'document', ['content_hash'], unique=False)
    safe_create_index(op.f('ix_document_gmt_deleted'), 'document', ['gmt_deleted'], unique=False)
    safe_create_index(op.f('ix_document_status'), 'document', ['status'], unique=False)
    safe_create_index(op.f('ix_document_user'), 'document', ['user'], unique=False)
    safe_create_unique_constraint('uq_document_collection_name_deleted', 'document', ['collection_id', 'name', 'gmt_deleted'])
    safe_create_index(op.f('ix_document_index_document_id'), 'document_index', ['document_id'], unique=False)
    safe_create_index(op.f('ix_document_index_id'), 'document_index', ['id'], unique=False)
    safe_create_index(op.f('ix_document_index_index_type'), 'document_index', ['index_type'], unique=False)
    safe_create_index(op.f('ix_document_index_status'), 'document_index', ['status'], unique=False)
    safe_create_unique_constraint('uq_document_index', 'document_index', ['document_id', 'index_type'])
    safe_create_index(op.f('ix_llm_provider_user_id'), 'llm_provider', ['user_id'], unique=False)
    safe_create_index(op.f('ix_message_feedback_gmt_deleted'), 'message_feedback', ['gmt_deleted'], unique=False)
    safe_create_index(op.f('ix_message_feedback_status'), 'message_feedback', ['status'], unique=False)
    safe_create_index(op.f('ix_message_feedback_user'), 'message_feedback', ['user'], unique=False)
    safe_create_unique_constraint('uq_feedback_chat_message_deleted', 'message_feedback', ['chat_id', 'message_id', 'gmt_deleted'])
    safe_create_index(op.f('ix_model_service_provider_name'), 'model_service_provider', ['name'], unique=False)
    safe_create_index(op.f('ix_model_service_provider_status'), 'model_service_provider', ['status'], unique=False)
    safe_create_unique_constraint('uq_model_service_provider_name_deleted', 'model_service_provider', ['name', 'gmt_deleted'])
    safe_create_index(op.f('ix_node_run_node_id'), 'node_run', ['node_id'], unique=False)
    safe_create_index(op.f('ix_node_run_run_id'), 'node_run', ['run_id'], unique=False)
    safe_create_index(op.f('ix_node_run_status'), 'node_run', ['status'], unique=False)
    op.create_foreign_key(None, 'node_run', 'workflow_run', ['run_id'], ['id'])
    safe_create_index(op.f('ix_oauth_account_account_id'), 'oauth_account', ['account_id'], unique=False)
    safe_create_index(op.f('ix_oauth_account_oauth_name'), 'oauth_account', ['oauth_name'], unique=False)
    op.create_foreign_key(None, 'oauth_account', 'user', ['user_id'], ['id'], ondelete='cascade')
    safe_create_index(op.f('ix_user_chat_collection_id'), 'user', ['chat_collection_id'], unique=False)
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['username'])
    safe_create_unique_constraint('idx_user_marketplace_history_unique', 'user_collection_subscription', ['user_id', 'collection_marketplace_id', 'gmt_deleted'])
    safe_create_index('idx_user_subscription_gmt_deleted', 'user_collection_subscription', ['gmt_deleted'], unique=False)
    safe_create_index('idx_user_subscription_marketplace', 'user_collection_subscription', ['collection_marketplace_id'], unique=False)
    safe_create_index('idx_user_subscription_user', 'user_collection_subscription', ['user_id'], unique=False)
    safe_create_index(op.f('ix_workflow_gmt_deleted'), 'workflow', ['gmt_deleted'], unique=False)
    safe_create_index(op.f('ix_workflow_status'), 'workflow', ['status'], unique=False)
    safe_create_index(op.f('ix_workflow_user'), 'workflow', ['user'], unique=False)
    safe_create_index(op.f('ix_workflow_run_execution_id'), 'workflow_run', ['execution_id'], unique=False)
    safe_create_index(op.f('ix_workflow_run_status'), 'workflow_run', ['status'], unique=False)
    safe_create_index(op.f('ix_workflow_run_user'), 'workflow_run', ['user'], unique=False)
    safe_create_index(op.f('ix_workflow_run_workflow_id'), 'workflow_run', ['workflow_id'], unique=False)
    op.create_foreign_key(None, 'workflow_run', 'workflow', ['workflow_id'], ['id'])
    safe_create_index(op.f('ix_workflow_version_user'), 'workflow_version', ['user'], unique=False)
    safe_create_index(op.f('ix_workflow_version_workflow_id'), 'workflow_version', ['workflow_id'], unique=False)
    safe_create_unique_constraint('uq_workflow_version', 'workflow_version', ['workflow_id', 'version'])
    op.create_foreign_key(None, 'workflow_version', 'workflow', ['workflow_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    op.drop_constraint(None, 'workflow_version', type_='foreignkey')
    op.drop_constraint('uq_workflow_version', 'workflow_version', type_='unique')
    op.drop_index(op.f('ix_workflow_version_workflow_id'), table_name='workflow_version')
    op.drop_index(op.f('ix_workflow_version_user'), table_name='workflow_version')
    op.drop_constraint(None, 'workflow_run', type_='foreignkey')
    op.drop_index(op.f('ix_workflow_run_workflow_id'), table_name='workflow_run')
    op.drop_index(op.f('ix_workflow_run_user'), table_name='workflow_run')
    op.drop_index(op.f('ix_workflow_run_status'), table_name='workflow_run')
    op.drop_index(op.f('ix_workflow_run_execution_id'), table_name='workflow_run')
    op.drop_index(op.f('ix_workflow_user'), table_name='workflow')
    op.drop_index(op.f('ix_workflow_status'), table_name='workflow')
    op.drop_index(op.f('ix_workflow_gmt_deleted'), table_name='workflow')
    op.drop_index('idx_user_subscription_user', table_name='user_collection_subscription')
    op.drop_index('idx_user_subscription_marketplace', table_name='user_collection_subscription')
    op.drop_index('idx_user_subscription_gmt_deleted', table_name='user_collection_subscription')
    op.drop_constraint('idx_user_marketplace_history_unique', 'user_collection_subscription', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_chat_collection_id'), table_name='user')
    op.drop_constraint(None, 'oauth_account', type_='foreignkey')
    op.drop_index(op.f('ix_oauth_account_oauth_name'), table_name='oauth_account')
    op.drop_index(op.f('ix_oauth_account_account_id'), table_name='oauth_account')
    op.drop_constraint(None, 'node_run', type_='foreignkey')
    op.drop_index(op.f('ix_node_run_status'), table_name='node_run')
    op.drop_index(op.f('ix_node_run_run_id'), table_name='node_run')
    op.drop_index(op.f('ix_node_run_node_id'), table_name='node_run')
    op.drop_constraint('uq_model_service_provider_name_deleted', 'model_service_provider', type_='unique')
    op.drop_index(op.f('ix_model_service_provider_status'), table_name='model_service_provider')
    op.drop_index(op.f('ix_model_service_provider_name'), table_name='model_service_provider')
    op.drop_constraint('uq_feedback_chat_message_deleted', 'message_feedback', type_='unique')
    op.drop_index(op.f('ix_message_feedback_user'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_status'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_gmt_deleted'), table_name='message_feedback')
    op.drop_index(op.f('ix_llm_provider_user_id'), table_name='llm_provider')
    op.drop_constraint('uq_document_index', 'document_index', type_='unique')
    op.drop_index(op.f('ix_document_index_status'), table_name='document_index')
    op.drop_index(op.f('ix_document_index_index_type'), table_name='document_index')
    op.drop_index(op.f('ix_document_index_id'), table_name='document_index')
    op.drop_index(op.f('ix_document_index_document_id'), table_name='document_index')
    op.drop_constraint('uq_document_collection_name_deleted', 'document', type_='unique')
    op.drop_index(op.f('ix_document_user'), table_name='document')
    op.drop_index(op.f('ix_document_status'), table_name='document')
    op.drop_index(op.f('ix_document_gmt_deleted'), table_name='document')
    op.drop_index(op.f('ix_document_content_hash'), table_name='document')
    op.drop_index(op.f('ix_document_collection_id'), table_name='document')
    op.drop_constraint('uq_collection_marketplace_collection', 'collection_marketplace', type_='unique')
    op.drop_index('idx_collection_marketplace_status', table_name='collection_marketplace')
    op.drop_index('idx_collection_marketplace_list', table_name='collection_marketplace')
    op.drop_index('idx_collection_marketplace_gmt_deleted', table_name='collection_marketplace')
    op.drop_index('idx_collection_marketplace_collection_id', table_name='collection_marketplace')
    op.drop_index(op.f('ix_collection_user'), table_name='collection')
    op.drop_index(op.f('ix_collection_status'), table_name='collection')
    op.drop_index(op.f('ix_collection_gmt_deleted'), table_name='collection')
    op.drop_index(op.f('ix_chat_message_message_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_created_at'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_chat_id'), table_name='chat_message')
    op.drop_constraint('uq_chat_agent_peer_deleted', 'chat', type_='unique')
    op.drop_index(op.f('ix_chat_user'), table_name='chat')
    op.drop_index(op.f('ix_chat_status'), table_name='chat')
    op.drop_index(op.f('ix_chat_gmt_deleted'), table_name='chat')
    op.drop_index(op.f('ix_chat_agent_id'), table_name='chat')
    op.alter_column('chat', 'agent_id',
               existing_type=mysql.VARCHAR(length=24),
               nullable=True)
    # 注意：出于与 upgrade() 相同的原因，这个 migration 不再管理
    # `audit_log` 表上的 idx_audit_* 系列索引，因此这里也不做 drop 操作。
    # Matching the upgrade() behavior above, we do not manage `agent` indexes
    # in this migration, so there is nothing to drop here either.
    if inspector.has_table('api_key'):
        op.drop_index(op.f('ix_api_key_user'), table_name='api_key')
        op.drop_index(op.f('ix_api_key_status'), table_name='api_key')
        op.drop_index(op.f('ix_api_key_is_system'), table_name='api_key')
        op.drop_index(op.f('ix_api_key_gmt_deleted'), table_name='api_key')
        op.drop_table('api_key')
    # ### end Alembic commands ###
