"""add workflow run tables

Revision ID: 4abd1756eeda
Revises: aac9cd19df75
Create Date: 2026-01-30 15:40:24.116176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4abd1756eeda'
down_revision: Union[str, None] = 'aac9cd19df75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_run',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('workflow_id', sa.String(length=24), nullable=True),
    sa.Column('workflow_version', sa.Integer(), nullable=True),
    sa.Column('user', sa.String(length=256), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_run_execution_id'), 'workflow_run', ['execution_id'], unique=False)
    op.create_index(op.f('ix_workflow_run_status'), 'workflow_run', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_run_user'), 'workflow_run', ['user'], unique=False)
    op.create_index(op.f('ix_workflow_run_workflow_id'), 'workflow_run', ['workflow_id'], unique=False)
    op.create_table('node_run',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('run_id', sa.String(length=24), nullable=False),
    sa.Column('node_id', sa.String(length=128), nullable=False),
    sa.Column('node_type', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=True),
    sa.Column('output_snapshot', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_run_node_id'), 'node_run', ['node_id'], unique=False)
    op.create_index(op.f('ix_node_run_run_id'), 'node_run', ['run_id'], unique=False)
    op.create_index(op.f('ix_node_run_status'), 'node_run', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_run_status'), table_name='node_run')
    op.drop_index(op.f('ix_node_run_run_id'), table_name='node_run')
    op.drop_index(op.f('ix_node_run_node_id'), table_name='node_run')
    op.drop_table('node_run')
    op.drop_index(op.f('ix_workflow_run_workflow_id'), table_name='workflow_run')
    op.drop_index(op.f('ix_workflow_run_user'), table_name='workflow_run')
    op.drop_index(op.f('ix_workflow_run_status'), table_name='workflow_run')
    op.drop_index(op.f('ix_workflow_run_execution_id'), table_name='workflow_run')
    op.drop_table('workflow_run')
    # ### end Alembic commands ###
