"""auto migration

Revision ID: caaf167c1b43
Revises: 
Create Date: 2026-08-26 14:13:15.687444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caaf167c1b43'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_gmt_deleted'), 'agent', ['gmt_deleted'], unique=False)
    op.create_index(op.f('ix_agent_status'), 'agent', ['status'], unique=False)
    op.create_index(op.f('ix_agent_user'), 'agent', ['user'], unique=False)
    op.create_table('api_key',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('user', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_gmt_deleted'), 'api_key', ['gmt_deleted'], unique=False)
    op.create_index(op.f('ix_api_key_is_system'), 'api_key', ['is_system'], unique=False)
    op.create_index(op.f('ix_api_key_status'), 'api_key', ['status'], unique=False)
    op.create_index(op.f('ix_api_key_user'), 'api_key', ['user'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True, comment='User ID'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='Username'),
    sa.Column('resource_type', sa.String(length=50), nullable=True, comment='Resource type'),
    sa.Column('resource_id', sa.String(length=255), nullable=True, comment='Resource ID (extracted at query time)'),
    sa.Column('api_name', sa.String(length=255), nullable=False, comment='API operation name'),
    sa.Column('http_method', sa.String(length=10), nullable=False, comment='HTTP method (POST, PUT, DELETE)'),
    sa.Column('path', sa.String(length=512), nullable=False, comment='API path'),
    sa.Column('status_code', sa.Integer(), nullable=True, comment='HTTP status code'),
    sa.Column('request_data', sa.Text(), nullable=True, comment='Request data (JSON)'),
    sa.Column('response_data', sa.Text(), nullable=True, comment='Response data (JSON)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if failed'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='User agent string'),
    sa.Column('request_id', sa.String(length=255), nullable=False, comment='Request ID for tracking'),
    sa.Column('start_time', sa.BigInteger(), nullable=False, comment='Request start time (milliseconds since epoch)'),
    sa.Column('end_time', sa.BigInteger(), nullable=True, comment='Request end time (milliseconds since epoch)'),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False, comment='Created time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_api_name', 'audit_log', ['api_name'], unique=False)
    op.create_index('idx_audit_gmt_created', 'audit_log', ['gmt_created'], unique=False)
    op.create_index('idx_audit_http_method', 'audit_log', ['http_method'], unique=False)
    op.create_index('idx_audit_request_id', 'audit_log', ['request_id'], unique=False)
    op.create_index('idx_audit_resource_id', 'audit_log', ['resource_id'], unique=False)
    op.create_index('idx_audit_resource_type', 'audit_log', ['resource_type'], unique=False)
    op.create_index('idx_audit_start_time', 'audit_log', ['start_time'], unique=False)
    op.create_index('idx_audit_status_code', 'audit_log', ['status_code'], unique=False)
    op.create_index('idx_audit_user_id', 'audit_log', ['user_id'], unique=False)
    op.create_table('chat',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user', sa.String(length=256), nullable=False),
    sa.Column('peer_type', sa.String(length=50), nullable=False),
    sa.Column('peer_id', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'peer_type', 'peer_id', 'gmt_deleted', name='uq_chat_agent_peer_deleted')
    )
    op.create_index(op.f('ix_chat_agent_id'), 'chat', ['agent_id'], unique=False)
    op.create_index(op.f('ix_chat_gmt_deleted'), 'chat', ['gmt_deleted'], unique=False)
    op.create_index(op.f('ix_chat_status'), 'chat', ['status'], unique=False)
    op.create_index(op.f('ix_chat_user'), 'chat', ['user'], unique=False)
    op.create_table('chat_message',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('message_id', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_message', sa.Text(), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_chat_id'), 'chat_message', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_message_created_at'), 'chat_message', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_message_message_id'), 'chat_message', ['message_id'], unique=False)
    op.create_table('collection',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_gmt_deleted'), 'collection', ['gmt_deleted'], unique=False)
    op.create_index(op.f('ix_collection_status'), 'collection', ['status'], unique=False)
    op.create_index(op.f('ix_collection_user'), 'collection', ['user'], unique=False)
    op.create_table('collection_marketplace',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('collection_id', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', name='uq_collection_marketplace_collection')
    )
    op.create_index('idx_collection_marketplace_collection_id', 'collection_marketplace', ['collection_id'], unique=False)
    op.create_index('idx_collection_marketplace_gmt_deleted', 'collection_marketplace', ['gmt_deleted'], unique=False)
    op.create_index('idx_collection_marketplace_list', 'collection_marketplace', ['status', 'gmt_created'], unique=False)
    op.create_index('idx_collection_marketplace_status', 'collection_marketplace', ['status'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('user', sa.String(length=256), nullable=False),
    sa.Column('collection_id', sa.String(length=24), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('object_path', sa.Text(), nullable=True),
    sa.Column('doc_metadata', sa.Text(), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'name', 'gmt_deleted', name='uq_document_collection_name_deleted')
    )
    op.create_index(op.f('ix_document_collection_id'), 'document', ['collection_id'], unique=False)
    op.create_index(op.f('ix_document_content_hash'), 'document', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_gmt_deleted'), 'document', ['gmt_deleted'], unique=False)
    op.create_index(op.f('ix_document_status'), 'document', ['status'], unique=False)
    op.create_index(op.f('ix_document_user'), 'document', ['user'], unique=False)
    op.create_table('document_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=24), nullable=False),
    sa.Column('index_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('observed_version', sa.Integer(), nullable=False),
    sa.Column('index_data', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_last_reconciled', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'index_type', name='uq_document_index')
    )
    op.create_index(op.f('ix_document_index_document_id'), 'document_index', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_index_id'), 'document_index', ['id'], unique=False)
    op.create_index(op.f('ix_document_index_index_type'), 'document_index', ['index_type'], unique=False)
    op.create_index(op.f('ix_document_index_status'), 'document_index', ['status'], unique=False)
    op.create_table('llm_provider',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('completion_dialect', sa.String(length=64), nullable=False),
    sa.Column('embedding_dialect', sa.String(length=64), nullable=False),
    sa.Column('rerank_dialect', sa.String(length=64), nullable=False),
    sa.Column('allow_custom_base_url', sa.Boolean(), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_llm_provider_user_id'), 'llm_provider', ['user_id'], unique=False)
    op.create_table('llm_provider_models',
    sa.Column('provider_name', sa.String(length=128), nullable=False),
    sa.Column('api', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=256), nullable=False),
    sa.Column('custom_llm_provider', sa.String(length=128), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('max_input_tokens', sa.Integer(), nullable=True),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('provider_name', 'api', 'model')
    )
    op.create_table('message_feedback',
    sa.Column('user', sa.String(length=256), nullable=False),
    sa.Column('chat_id', sa.String(length=24), nullable=False),
    sa.Column('message_id', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('original_answer', sa.Text(), nullable=True),
    sa.Column('revised_answer', sa.Text(), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('chat_id', 'message_id'),
    sa.UniqueConstraint('chat_id', 'message_id', 'gmt_deleted', name='uq_feedback_chat_message_deleted')
    )
    op.create_index(op.f('ix_message_feedback_gmt_deleted'), 'message_feedback', ['gmt_deleted'], unique=False)
    op.create_index(op.f('ix_message_feedback_status'), 'message_feedback', ['status'], unique=False)
    op.create_index(op.f('ix_message_feedback_user'), 'message_feedback', ['user'], unique=False)
    op.create_table('model_service_provider',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.String(length=256), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'gmt_deleted', name='uq_model_service_provider_name_deleted')
    )
    op.create_index(op.f('ix_model_service_provider_name'), 'model_service_provider', ['name'], unique=False)
    op.create_index(op.f('ix_model_service_provider_status'), 'model_service_provider', ['status'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('chat_collection_id', sa.String(length=24), nullable=True),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_chat_collection_id'), 'user', ['chat_collection_id'], unique=False)
    op.create_table('user_collection_subscription',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.String(length=24), nullable=False),
    sa.Column('collection_marketplace_id', sa.String(length=24), nullable=False),
    sa.Column('gmt_subscribed', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'collection_marketplace_id', 'gmt_deleted', name='idx_user_marketplace_history_unique')
    )
    op.create_index('idx_user_subscription_gmt_deleted', 'user_collection_subscription', ['gmt_deleted'], unique=False)
    op.create_index('idx_user_subscription_marketplace', 'user_collection_subscription', ['collection_marketplace_id'], unique=False)
    op.create_index('idx_user_subscription_user', 'user_collection_subscription', ['user_id'], unique=False)
    op.create_table('workflow',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('graph', sa.JSON(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_gmt_deleted'), 'workflow', ['gmt_deleted'], unique=False)
    op.create_index(op.f('ix_workflow_status'), 'workflow', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_user'), 'workflow', ['user'], unique=False)
    op.create_table('oauth_account',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.String(length=24), nullable=False),
    sa.Column('oauth_name', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(length=1024), nullable=True),
    sa.Column('account_id', sa.String(length=320), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_account_account_id'), 'oauth_account', ['account_id'], unique=False)
    op.create_index(op.f('ix_oauth_account_oauth_name'), 'oauth_account', ['oauth_name'], unique=False)
    op.create_table('workflow_run',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('workflow_id', sa.String(length=24), nullable=True),
    sa.Column('workflow_version', sa.Integer(), nullable=True),
    sa.Column('user', sa.String(length=256), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_run_execution_id'), 'workflow_run', ['execution_id'], unique=False)
    op.create_index(op.f('ix_workflow_run_status'), 'workflow_run', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_run_user'), 'workflow_run', ['user'], unique=False)
    op.create_index(op.f('ix_workflow_run_workflow_id'), 'workflow_run', ['workflow_id'], unique=False)
    op.create_table('workflow_version',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('workflow_id', sa.String(length=24), nullable=False),
    sa.Column('user', sa.String(length=256), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('graph', sa.JSON(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('save_type', sa.String(length=64), nullable=False),
    sa.Column('autosave_metadata', sa.JSON(), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'version', name='uq_workflow_version')
    )
    op.create_index(op.f('ix_workflow_version_user'), 'workflow_version', ['user'], unique=False)
    op.create_index(op.f('ix_workflow_version_workflow_id'), 'workflow_version', ['workflow_id'], unique=False)
    op.create_table('node_run',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('run_id', sa.String(length=24), nullable=False),
    sa.Column('node_id', sa.String(length=128), nullable=False),
    sa.Column('node_type', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=True),
    sa.Column('output_snapshot', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_run_node_id'), 'node_run', ['node_id'], unique=False)
    op.create_index(op.f('ix_node_run_run_id'), 'node_run', ['run_id'], unique=False)
    op.create_index(op.f('ix_node_run_status'), 'node_run', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_run_status'), table_name='node_run')
    op.drop_index(op.f('ix_node_run_run_id'), table_name='node_run')
    op.drop_index(op.f('ix_node_run_node_id'), table_name='node_run')
    op.drop_table('node_run')
    op.drop_index(op.f('ix_workflow_version_workflow_id'), table_name='workflow_version')
    op.drop_index(op.f('ix_workflow_version_user'), table_name='workflow_version')
    op.drop_table('workflow_version')
    op.drop_index(op.f('ix_workflow_run_workflow_id'), table_name='workflow_run')
    op.drop_index(op.f('ix_workflow_run_user'), table_name='workflow_run')
    op.drop_index(op.f('ix_workflow_run_status'), table_name='workflow_run')
    op.drop_index(op.f('ix_workflow_run_execution_id'), table_name='workflow_run')
    op.drop_table('workflow_run')
    op.drop_index(op.f('ix_oauth_account_oauth_name'), table_name='oauth_account')
    op.drop_index(op.f('ix_oauth_account_account_id'), table_name='oauth_account')
    op.drop_table('oauth_account')
    op.drop_index(op.f('ix_workflow_user'), table_name='workflow')
    op.drop_index(op.f('ix_workflow_status'), table_name='workflow')
    op.drop_index(op.f('ix_workflow_gmt_deleted'), table_name='workflow')
    op.drop_table('workflow')
    op.drop_index('idx_user_subscription_user', table_name='user_collection_subscription')
    op.drop_index('idx_user_subscription_marketplace', table_name='user_collection_subscription')
    op.drop_index('idx_user_subscription_gmt_deleted', table_name='user_collection_subscription')
    op.drop_table('user_collection_subscription')
    op.drop_index(op.f('ix_user_chat_collection_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_model_service_provider_status'), table_name='model_service_provider')
    op.drop_index(op.f('ix_model_service_provider_name'), table_name='model_service_provider')
    op.drop_table('model_service_provider')
    op.drop_index(op.f('ix_message_feedback_user'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_status'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_gmt_deleted'), table_name='message_feedback')
    op.drop_table('message_feedback')
    op.drop_table('llm_provider_models')
    op.drop_index(op.f('ix_llm_provider_user_id'), table_name='llm_provider')
    op.drop_table('llm_provider')
    op.drop_index(op.f('ix_document_index_status'), table_name='document_index')
    op.drop_index(op.f('ix_document_index_index_type'), table_name='document_index')
    op.drop_index(op.f('ix_document_index_id'), table_name='document_index')
    op.drop_index(op.f('ix_document_index_document_id'), table_name='document_index')
    op.drop_table('document_index')
    op.drop_index(op.f('ix_document_user'), table_name='document')
    op.drop_index(op.f('ix_document_status'), table_name='document')
    op.drop_index(op.f('ix_document_gmt_deleted'), table_name='document')
    op.drop_index(op.f('ix_document_content_hash'), table_name='document')
    op.drop_index(op.f('ix_document_collection_id'), table_name='document')
    op.drop_table('document')
    op.drop_index('idx_collection_marketplace_status', table_name='collection_marketplace')
    op.drop_index('idx_collection_marketplace_list', table_name='collection_marketplace')
    op.drop_index('idx_collection_marketplace_gmt_deleted', table_name='collection_marketplace')
    op.drop_index('idx_collection_marketplace_collection_id', table_name='collection_marketplace')
    op.drop_table('collection_marketplace')
    op.drop_index(op.f('ix_collection_user'), table_name='collection')
    op.drop_index(op.f('ix_collection_status'), table_name='collection')
    op.drop_index(op.f('ix_collection_gmt_deleted'), table_name='collection')
    op.drop_table('collection')
    op.drop_index(op.f('ix_chat_message_message_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_created_at'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_chat_id'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index(op.f('ix_chat_user'), table_name='chat')
    op.drop_index(op.f('ix_chat_status'), table_name='chat')
    op.drop_index(op.f('ix_chat_gmt_deleted'), table_name='chat')
    op.drop_index(op.f('ix_chat_agent_id'), table_name='chat')
    op.drop_table('chat')
    op.drop_index('idx_audit_user_id', table_name='audit_log')
    op.drop_index('idx_audit_status_code', table_name='audit_log')
    op.drop_index('idx_audit_start_time', table_name='audit_log')
    op.drop_index('idx_audit_resource_type', table_name='audit_log')
    op.drop_index('idx_audit_resource_id', table_name='audit_log')
    op.drop_index('idx_audit_request_id', table_name='audit_log')
    op.drop_index('idx_audit_http_method', table_name='audit_log')
    op.drop_index('idx_audit_gmt_created', table_name='audit_log')
    op.drop_index('idx_audit_api_name', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_api_key_user'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_status'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_is_system'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_gmt_deleted'), table_name='api_key')
    op.drop_table('api_key')
    op.drop_index(op.f('ix_agent_user'), table_name='agent')
    op.drop_index(op.f('ix_agent_status'), table_name='agent')
    op.drop_index(op.f('ix_agent_gmt_deleted'), table_name='agent')
    op.drop_table('agent')
    # ### end Alembic commands ###
