"""empty message

Revision ID: e7990543ab3e
Revises: 9704dd11d94e
Create Date: 2026-01-25 04:02:48.511743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7990543ab3e'
down_revision: Union[str, None] = '9704dd11d94e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - indexes creation removed ###
    op.add_column('chat_message', sa.Column('role', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - indexes removal removed ###
    op.drop_column('chat_message', 'role')
    # ### end Alembic commands ###
