"""auto migration

Revision ID: 8ed9487ae8c9
Revises: e7990543ab3e
Create Date: 2026-01-27 02:41:49.956912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed9487ae8c9'
down_revision: Union[str, None] = 'e7990543ab3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True, comment='User ID'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='Username'),
    sa.Column('resource_type', sa.String(length=50), nullable=True, comment='Resource type'),
    sa.Column('resource_id', sa.String(length=255), nullable=True, comment='Resource ID (extracted at query time)'),
    sa.Column('api_name', sa.String(length=255), nullable=False, comment='API operation name'),
    sa.Column('http_method', sa.String(length=10), nullable=False, comment='HTTP method (POST, PUT, DELETE)'),
    sa.Column('path', sa.String(length=512), nullable=False, comment='API path'),
    sa.Column('status_code', sa.Integer(), nullable=True, comment='HTTP status code'),
    sa.Column('request_data', sa.Text(), nullable=True, comment='Request data (JSON)'),
    sa.Column('response_data', sa.Text(), nullable=True, comment='Response data (JSON)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if failed'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='User agent string'),
    sa.Column('request_id', sa.String(length=255), nullable=False, comment='Request ID for tracking'),
    sa.Column('start_time', sa.BigInteger(), nullable=False, comment='Request start time (milliseconds since epoch)'),
    sa.Column('end_time', sa.BigInteger(), nullable=True, comment='Request end time (milliseconds since epoch)'),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False, comment='Created time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_api_name', 'audit_log', ['api_name'], unique=False)
    op.create_index('idx_audit_gmt_created', 'audit_log', ['gmt_created'], unique=False)
    op.create_index('idx_audit_http_method', 'audit_log', ['http_method'], unique=False)
    op.create_index('idx_audit_request_id', 'audit_log', ['request_id'], unique=False)
    op.create_index('idx_audit_resource_id', 'audit_log', ['resource_id'], unique=False)
    op.create_index('idx_audit_resource_type', 'audit_log', ['resource_type'], unique=False)
    op.create_index('idx_audit_start_time', 'audit_log', ['start_time'], unique=False)
    op.create_index('idx_audit_status_code', 'audit_log', ['status_code'], unique=False)
    op.create_index('idx_audit_user_id', 'audit_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_bot_gmt_deleted'), 'bot', ['gmt_deleted'], unique=False)
    op.create_index(op.f('ix_bot_status'), 'bot', ['status'], unique=False)
    op.create_index(op.f('ix_bot_user'), 'bot', ['user'], unique=False)
    op.create_index(op.f('ix_chat_bot_id'), 'chat', ['bot_id'], unique=False)
    op.create_index(op.f('ix_chat_gmt_deleted'), 'chat', ['gmt_deleted'], unique=False)
    op.create_index(op.f('ix_chat_status'), 'chat', ['status'], unique=False)
    op.create_index(op.f('ix_chat_user'), 'chat', ['user'], unique=False)
    op.create_unique_constraint('uq_chat_bot_peer_deleted', 'chat', ['bot_id', 'peer_type', 'peer_id', 'gmt_deleted'])
    op.create_index(op.f('ix_chat_message_chat_id'), 'chat_message', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_message_created_at'), 'chat_message', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_message_message_id'), 'chat_message', ['message_id'], unique=False)
    op.create_index(op.f('ix_collection_gmt_deleted'), 'collection', ['gmt_deleted'], unique=False)
    op.create_index(op.f('ix_collection_status'), 'collection', ['status'], unique=False)
    op.create_index(op.f('ix_collection_user'), 'collection', ['user'], unique=False)
    op.create_index(op.f('ix_document_collection_id'), 'document', ['collection_id'], unique=False)
    op.create_index(op.f('ix_document_content_hash'), 'document', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_gmt_deleted'), 'document', ['gmt_deleted'], unique=False)
    op.create_index(op.f('ix_document_status'), 'document', ['status'], unique=False)
    op.create_index(op.f('ix_document_user'), 'document', ['user'], unique=False)
    op.create_unique_constraint('uq_document_collection_name_deleted', 'document', ['collection_id', 'name', 'gmt_deleted'])
    op.create_index(op.f('ix_document_index_document_id'), 'document_index', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_index_id'), 'document_index', ['id'], unique=False)
    op.create_index(op.f('ix_document_index_index_type'), 'document_index', ['index_type'], unique=False)
    op.create_index(op.f('ix_document_index_status'), 'document_index', ['status'], unique=False)
    op.create_unique_constraint('uq_document_index', 'document_index', ['document_id', 'index_type'])
    op.create_index(op.f('ix_llm_provider_user_id'), 'llm_provider', ['user_id'], unique=False)
    op.create_index(op.f('ix_message_feedback_gmt_deleted'), 'message_feedback', ['gmt_deleted'], unique=False)
    op.create_index(op.f('ix_message_feedback_status'), 'message_feedback', ['status'], unique=False)
    op.create_index(op.f('ix_message_feedback_user'), 'message_feedback', ['user'], unique=False)
    op.create_unique_constraint('uq_feedback_chat_message_deleted', 'message_feedback', ['chat_id', 'message_id', 'gmt_deleted'])
    op.create_index(op.f('ix_model_service_provider_name'), 'model_service_provider', ['name'], unique=False)
    op.create_index(op.f('ix_model_service_provider_status'), 'model_service_provider', ['status'], unique=False)
    op.create_unique_constraint('uq_model_service_provider_name_deleted', 'model_service_provider', ['name', 'gmt_deleted'])
    op.create_index(op.f('ix_oauth_account_account_id'), 'oauth_account', ['account_id'], unique=False)
    op.create_index(op.f('ix_oauth_account_oauth_name'), 'oauth_account', ['oauth_name'], unique=False)
    op.create_foreign_key(None, 'oauth_account', 'user', ['user_id'], ['id'], ondelete='cascade')
    op.create_index(op.f('ix_user_chat_collection_id'), 'user', ['chat_collection_id'], unique=False)
    op.create_unique_constraint(None, 'user', ['username'])
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_chat_collection_id'), table_name='user')
    op.drop_constraint(None, 'oauth_account', type_='foreignkey')
    op.drop_index(op.f('ix_oauth_account_oauth_name'), table_name='oauth_account')
    op.drop_index(op.f('ix_oauth_account_account_id'), table_name='oauth_account')
    op.drop_constraint('uq_model_service_provider_name_deleted', 'model_service_provider', type_='unique')
    op.drop_index(op.f('ix_model_service_provider_status'), table_name='model_service_provider')
    op.drop_index(op.f('ix_model_service_provider_name'), table_name='model_service_provider')
    op.drop_constraint('uq_feedback_chat_message_deleted', 'message_feedback', type_='unique')
    op.drop_index(op.f('ix_message_feedback_user'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_status'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_gmt_deleted'), table_name='message_feedback')
    op.drop_index(op.f('ix_llm_provider_user_id'), table_name='llm_provider')
    op.drop_constraint('uq_document_index', 'document_index', type_='unique')
    op.drop_index(op.f('ix_document_index_status'), table_name='document_index')
    op.drop_index(op.f('ix_document_index_index_type'), table_name='document_index')
    op.drop_index(op.f('ix_document_index_id'), table_name='document_index')
    op.drop_index(op.f('ix_document_index_document_id'), table_name='document_index')
    op.drop_constraint('uq_document_collection_name_deleted', 'document', type_='unique')
    op.drop_index(op.f('ix_document_user'), table_name='document')
    op.drop_index(op.f('ix_document_status'), table_name='document')
    op.drop_index(op.f('ix_document_gmt_deleted'), table_name='document')
    op.drop_index(op.f('ix_document_content_hash'), table_name='document')
    op.drop_index(op.f('ix_document_collection_id'), table_name='document')
    op.drop_index(op.f('ix_collection_user'), table_name='collection')
    op.drop_index(op.f('ix_collection_status'), table_name='collection')
    op.drop_index(op.f('ix_collection_gmt_deleted'), table_name='collection')
    op.drop_index(op.f('ix_chat_message_message_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_created_at'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_chat_id'), table_name='chat_message')
    op.drop_constraint('uq_chat_bot_peer_deleted', 'chat', type_='unique')
    op.drop_index(op.f('ix_chat_user'), table_name='chat')
    op.drop_index(op.f('ix_chat_status'), table_name='chat')
    op.drop_index(op.f('ix_chat_gmt_deleted'), table_name='chat')
    op.drop_index(op.f('ix_chat_bot_id'), table_name='chat')
    op.drop_index(op.f('ix_bot_user'), table_name='bot')
    op.drop_index(op.f('ix_bot_status'), table_name='bot')
    op.drop_index(op.f('ix_bot_gmt_deleted'), table_name='bot')
    op.drop_index('idx_audit_user_id', table_name='audit_log')
    op.drop_index('idx_audit_status_code', table_name='audit_log')
    op.drop_index('idx_audit_start_time', table_name='audit_log')
    op.drop_index('idx_audit_resource_type', table_name='audit_log')
    op.drop_index('idx_audit_resource_id', table_name='audit_log')
    op.drop_index('idx_audit_request_id', table_name='audit_log')
    op.drop_index('idx_audit_http_method', table_name='audit_log')
    op.drop_index('idx_audit_gmt_created', table_name='audit_log')
    op.drop_index('idx_audit_api_name', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
